/*
 *
 * Header constants
 *
 */

export const SET_CURRENT_SESSION_LOADING = 'app/Header/SET_CURRENT_SESSION_LOADING';
export const SET_CURRENT_SESSION_SUCCESS = 'app/Header/SET_CURRENT_SESSION_SUCCESS';
export const SET_CURRENT_SESSION_FAILURE = 'app/Header/SET_CURRENT_SESSION_FAILURE';

export const SETTING_ENCOUNTER_ROLE_SUCCESS = 'app/Header/SETTING_ENCOUNTER_ROLE_SUCCESS';
export const SETTING_ENCOUNTER_ROLE_FAILURE = 'app/Header/SETTING_ENCOUNTER_ROLE_FAILURE';
export const SETTING_ENCOUNTER_ROLE_LOADING = 'app/Header/SETTING_ENCOUNTER_ROLE_LOADING';

export const SETTING_ENCOUNTER_TYPE_SUCCESS = 'app/Header/SETTING_ENCOUNTER_TYPE_SUCCESS';
export const SETTING_ENCOUNTER_TYPE_FAILURE = 'app/Header/SETTING_ENCOUNTER_TYPE_FAILURE';
export const SETTING_ENCOUNTER_TYPE_LOADING = 'app/Header/SETTING_ENCOUNTER_TYPE_LOADING';

export const FETCH_ENCOUNTER_TYPE_LOADING = "app/Header/FETCH_ENCOUNTER_TYPE_LOADING";
export const FETCH_ENCOUNTER_TYPE_SUCCESS = "app/Header/FETCH_ENCOUNTER_TYPE_SUCCESS";
export const FETCH_ENCOUNTER_TYPE_FAILURE = "app/Header/FETCH_ENCOUNTER_TYPE_FAILURE";

export const FETCH_ENCOUNTER_ROLE_LOADING = "app/Header/FETCH_ENCOUNTER_ROLE_LOADING";
export const FETCH_ENCOUNTER_ROLE_SUCCESS = "app/Header/FETCH_ENCOUNTER_ROLE_SUCCESS";
export const FETCH_ENCOUNTER_ROLE_FAILURE = "app/Header/FETCH_ENCOUNTER_ROLE_FAILURE";

export const FETCH_ENCOUNTERS_LOADING = "app/Header/FETCH_ENCOUNTERS_LOADING";
export const FETCH_ENCOUNTERS_SUCCESS = "app/Header/FETCH_ENCOUNTERS_SUCCESS";
export const FETCH_ENCOUNTERS_FAILURE = "app/Header/FETCH_ENCOUNTERS_FAILURE";

export const CREATE_ENCOUNTER_LOADING = "app/Header/CREATE_ENCOUNTER_LOADING";
export const CREATE_ENCOUNTER_SUCCESS = "app/Header/CREATE_ENCOUNTER_SUCCESS";
export const CREATE_ENCOUNTER_FAILURE = "app/Header/CREATE_ENCOUNTER_FAILURE";

export const LOAD_PATIENT = 'app/Header/LOAD_PATIENT';
export const LOAD_PATIENT_SUCCESS = 'app/Header/LOAD_PATIENT_SUCCESS';
export const LOAD_PATIENT_ERROR = 'app/Header/LOAD_PATIENT_ERROR';

export const FETCH_ORDER_GROUP_LOADING = "app/Header/FETCH_ORDER_GROUP_LOADING";
export const FETCH_ORDER_GROUP_SUCCESS = "app/Header/FETCH_ORDER_GROUP_SUCCESS";
export const FETCH_ORDER_GROUP_FAILURE = "app/Header/FETCH_ORDER_GROUP_FAILURE";

export const FETCH_OBSERVATIONS_LOADING = 'app/Header/FETCH_OBSERVATIONS_LOADING';
export const FETCH_OBSERVATIONS_SUCCESS = 'app/Header/FETCH_OBSERVATIONS_SUCCESS';
export const FETCH_OBSERVATIONS_FAILURE = 'app/Header/FETCH_OBSERVATIONS_FAILURE';

export const LOAD_EXTENDED_ORDER_GROUPS = 'app/Header/LOAD_EXTENDED_ORDER_GROUPS';
export const LOAD_EXTENDED_ORDER_GROUPS_SUCCESS = 'app/Header/LOAD_EXTENDED_ORDER_GROUPS_SUCCESS';
export const LOAD_EXTENDED_ORDER_GROUPS_ERROR = 'app/Header/LOAD_EXTENDED_ORDER_GROUPS_ERROR';
