/*
 *
 * Header constants
 *
 */

export const DEFAULT_ACTION = 'app/Header/DEFAULT_ACTION';
export const SET_CURRENT_SESSION_LOADING = 'app/Header/SET_CURRENT_SESSION_LOADING';
export const SET_CURRENT_SESSION_SUCCESS = 'app/Header/SET_CURRENT_SESSION_SUCCESS';
export const SET_CURRENT_SESSION_ERROR = 'app/Header/SET_CURRENT_SESSION_ERROR';
export const SETTING_ENCOUNTER_ROLE_SUCCESS = 'app/Header/SETTING_ENCOUNTER_ROLE_SUCCESS';
export const SETTING_ENCOUNTER_ROLE_FAILURE = 'app/Header/SETTING_ENCOUNTER_ROLE_FAILURE';
export const SETTING_ENCOUNTER_ROLE_LOADING = 'app/Header/SETTING_ENCOUNTER_ROLE_LOADING';
export const SETTING_ENCOUNTER_TYPE_SUCCESS = 'app/Header/SETTING_ENCOUNTER_TYPE_SUCCESS';
export const SETTING_ENCOUNTER_TYPE_FAILURE = 'app/Header/SETTING_ENCOUNTER_TYPE_FAILURE';
export const SETTING_ENCOUNTER_TYPE_LOADING = 'app/Header/SETTING_ENCOUNTER_TYPE_LOADING';
